### ISSUE TITLE
Add support for Ghost navigation

### ISSUE THREAD

**Issue by mihneadb** [mihneadb/no-nonsense#19]
Docs: http://themes.ghost.org/v0.5.9/docs/navigation

- [ ] integrate Ghost navigation in the nav helper
- [ ] drop the old logic
- [ ] update the readme

**Comment by mihneadb** [comment]
Added steps + link to docs.

**Comment by issmirnov** [comment]
Hey,

Had some time to take a look. Converting the nav logic to use the new helper isn't too hard, however, I'm having some issues with the Home link. With the current nav.hbs, the home link appears on all pages but the actual home page. However, with the new navigation helper we are stuck into the #navigation environment, so the `if #tag` conditionals don't work anymore. 

What do you want to do?

https://github.com/issmirnov/no-nonsense/tree/issue19-nav

**Comment by mihneadb** [comment]
Hey there, thanks for taking the time! :beers: 

I guess we can simply default to what Ghost does (i.e. show the Home all the time). Should be fine.

**Comment by issmirnov** [comment]
Hey,

I defaulted to ghost's behavior for the navigation. Also found a way to implement a hack to substitute in the tag's rss link rather than blog's global one. 

Take a look at the code, I think it's ready. Might be some whitespace issues, but seeing as that's a matter of preference I defer that to you.

Best!

**Comment by mihneadb** [comment]
Closed via #20. Thanks!
